insert into ourclients ( id, caption ) values ( 1, 'Коммерц Pro' );
insert into ourclients ( id, caption ) values ( 2, 'ТрейдТорг' );
insert into ourclients ( id, caption ) values ( 3, 'goodzone' );
insert into ourclients ( id, caption ) values ( 4, 'Хобия' );
insert into ourclients ( id, caption ) values ( 5, 'МедСнаб' );
insert into ourclients ( id, caption ) values ( 6, 'АлкоСбыт' );
insert into ourclients ( id, caption ) values ( 7, 'Регион-Трейдинг' );
insert into ourclients ( id, caption ) values ( 8, 'ТрейдСтандарт' );
insert into ourclients ( id, caption ) values ( 9, 'ЭкономМаркет' );
insert into ourclients ( id, caption ) values ( 10, 'ОткатКонтора' );
insert into ourclients ( id, caption ) values ( 11, 'СтандартИндустрия' );
insert into ourclients ( id, caption ) values ( 12, 'МонолитТехно' );
insert into ourclients ( id, caption ) values ( 13, 'МастерАрхитект' );
insert into ourclients ( id, caption ) values ( 14, 'Прорабыч' );
insert into ourclients ( id, caption ) values ( 15, 'СнабМонолит' );
insert into ourclients ( id, caption ) values ( 16, 'КирпичТехника' );
insert into ourclients ( id, caption ) values ( 17, 'Экстрастрой' );
insert into ourclients ( id, caption ) values ( 18, 'STIMСтрой' );
insert into ourclients ( id, caption ) values ( 19, 'СнабБригада' );
insert into ourclients ( id, caption ) values ( 20, 'Swift Ремонт' );
insert into ourclients ( id, caption ) values ( 21, 'ПрофВояж' );
insert into ourclients ( id, caption ) values ( 22, 'ЗагранЭкстрим' );
insert into ourclients ( id, caption ) values ( 23, 'Сувенир tur ' );
insert into ourclients ( id, caption ) values ( 24, 'Загранка' );
insert into ourclients ( id, caption ) values ( 25, 'СтандартТрэвэл' );
insert into ourclients ( id, caption ) values ( 26, 'ЭкоТранзит' );
insert into ourclients ( id, caption ) values ( 27, 'ВояжВсемъ' );
insert into ourclients ( id, caption ) values ( 28, 'Путевочка' );
insert into ourclients ( id, caption ) values ( 29, 'ЛюксВояж' );
insert into ourclients ( id, caption ) values ( 30, 'ТурДеМир' );