DECLARE
 totalsum NUMBER(16, 2 );
begin
SELECT sum( CURRENTDEBT.DEBTSUM ) into totalsum
from CURRENTDEBT
JOIN MYCLIENT on CURRENTDEBT.IDCLIENT = MYCLIENT.ID
and CURRENTDEBT.DEBTSUM > MYCLIENT.DEBTLIMIT;
DBMS_OUTPUT.put_line( totalsum );
end;